# Generated by Django 5.2.7 on 2025-10-18 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['-created_at'], 'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='nome',
        ),
        migrations.AddField(
            model_name='motorista',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_categoria',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=5, null=True, verbose_name='Categoria CNH'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da CNH'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='estado',
            field=models.CharField(blank=True, choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('DF', 'Distrito Federal')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto 3x4 do motorista', null=True, upload_to='motoristas/fotos/', verbose_name='Foto do Motorista'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='nome_completo',
            field=models.CharField(default='Motorista Sem Nome', max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorista',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('FERIAS', 'Férias'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
