# Generated by Django 5.2.7 on 2025-10-22 18:38

import drivers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_motorista_cpf_alter_motorista_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cnh_categoria',
            field=models.CharField(blank=True, choices=[('E', 'E')], max_length=5, null=True, validators=[drivers.validators.validar_categoria_cnh], verbose_name='Categoria CNH'),
        ),
    ]
