# Generated by Django 5.2.7 on 2025-10-27 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_motorista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='mei_numero',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='MEI deve estar no formato: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='Número do MEI'),
        ),
    ]
